### ISSUE TITLE
Considerations for `reflection.md`

### ISSUE THREAD

**Issue by reikookamoto** [UBC-MDS/DSCI_532_group-106_R_supermarket#21]
- There's 4 figures in each section, top-left figure always has isssues rendering (it's shrunk and derpy compared to the other figures)
   - When you give it a few seconds, it matches the dimensions of the other figures
- Legends in the heat maps also looks derpy
- Tool tip of the heat map has underscores between words
- Couldn't remove Plotly logo and toolbar - We couldn't seem to review it even after asking Firas
- app.Py adding docstrings to the code, change camel case to snake case

**Comment by reikookamoto** [comment]
Commenting on #22 

- "This may be a useful functionality if our manager was staffing for Black Friday weekend and want**ed** to see store performance details **during** previous holiday weekends." 
- "Days of the week and time**s** of day are selected separately and combinations of choices are not possible."
- "Improving this would require readjusting the legends so that a common scale is used for all charts no matter the selection." <-- I'm not quite sure I understand why this would be the fix
- "We need to update the tooltip so that it shows the value of the selection." <-- Maybe just provide an example instead (i.e. we need to change "Time_of_day" to "Time of day"). You could also say that although the underscores are distracting, they still relay the message across.
- Maybe mention that Firas asked the developers to re-open the issue regarding the modebar

@moniquewong

**Comment by moniquewong** [comment]
@reikookamoto I think our Python app shows the values on the tooltip. From a user point of view, that's probably the most informative tooltip instead of re-emphasizing what's already shown on the x / y axis. 

Fixed all others and will be making a pull request soon.
